name: Check Lua Syntax

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4  # Możesz wybrać wersję Lua, której używasz

      - name: Check Lua syntax
        run: |
          for file in $(find ./custom_scripts -name '*.lua'); do
            echo "Processing $file"
            
            # Tworzenie tymczasowego pliku bez linijek z '->'
            grep -v '\->' "$file" > "$file.tmp"
            
            # Sprawdzanie składni w przetworzonym pliku
            if ! luac -p "$file.tmp"; then
              echo "Syntax error in $file (excluding lines with '->')"
              rm "$file.tmp"
              exit 1
            fi
            
            # Usuwanie tymczasowego pliku
            rm "$file.tmp"
          done
